### ISSUE TITLE
client_id/secret doesn't actually work

### ISSUE THREAD

**Issue by jrochkind** [sportngin/hubstats#117]
in progress of trying to set up hubstats to check it out. 

Generating and setting a client_id/secret doesn't seem to actually work. Perhaps Github changed the way their auth works. 

~~~
Octokit::Unauthorized: GET https://api.github.com/user?client_id=6e677d922cc430f533f4&client_secret=(redacted): 401 - Requires authentication // See: https://developer.github.com/v3
~~~

But an access token works (at least so far), and is prob the better choice anyway in this case. Docs and/or code should prob be updated to only use access token.

**Comment by emmasax1** [comment]
Good to know. We personally always authenticate with the `access_token`, so I guess we didn't realize that the `client_id` and `secret` have a bug. I'll update the documentation accordingly.

**Comment by emmasax1** [comment]
Fixed in https://github.com/sportngin/hubstats/pull/123
