### ISSUE TITLE
Setup fails on pull repos comments, seems to be emojis encoding problem

### ISSUE THREAD

**Issue by pilipenok** [sportngin/hubstats#122]
```
Adding comments to sportngin/mobile_service

rake aborted!

ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value: '\xF0\x9F\x91\x8D ' for column 'body' at row 1: INSERT INTO `hubstats_comments` (`id`, `kind`, `user_id`, `pull_request_id`, `repo_id`, `created_at`, `updated_at`, `path`, `html_url`, `url`, `pull_request_url`, `body`) VALUES (96615073, 'PullRequest', 1328587, 102023301, 44784215, '2017-01-18 11:29:17', '2017-01-18 14:44:18', 0, 'https://github.com/sportngin/mobile_service/pull/69#discussion_r96615073', 'https://api.github.com/repos/sportngin/mobile_service/pulls/comments/96615073', 'https://api.github.com/repos/sportngin/mobile_service/pulls/69', 'Nice 👍 ')
```

Found possible fix on https://stackoverflow.com/questions/22464011/mysql2error-incorrect-string-value

**Comment by emmasax1** [comment]
Yes, we've noticed that when there are emojis in the comments descriptions, this tends to fail. In the past, we've tried to fix this issue by making the comments column in the `hubstats_pull_requests` table into type `text` instead of `string`.

**Comment by pilipenok** [comment]
I fixed the same issue on ngin. 
This is only due to mysql collation, not a type

**Comment by emmasax1** [comment]
Ah interesting. Good to know. Can you Slack me what you did to Ngin?

**Comment by emmasax1** [comment]
Note for the public: This is fixable from within the individual repositories connected to Hubstats.
