### ISSUE TITLE
More setup issues

### ISSUE THREAD

**Issue by martinmalek** [sportngin/hubstats#126]
Hi

Could you tell me what version of RoR you are using?

Rake fails because of jobs being declared as rake app:hubstats:xxxx and but in the code they are only hubstats:xxxx

**Comment by emmasax1** [comment]
Hi Martin.
```
emmasax@EmmasMacbook hubstats (master)$ rails -v
Rails 4.2.5
emmasax@EmmasMacbook hubstats (master)$ ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
```

In regards to the question you emailed me, I'm going to repost it here:

> I’m trying to follow the instructions of https://github.com/sportngin/hubstats but I’m getting tons of errors of missing rake jobs.
>
> ```
> hubstats [master●●] % rails generate hubstats:install
> Could not find generator 'hubstats:install'. Maybe you meant 'js:assets', 'css:assets' or 'test_unit:model'
> Run `rails generate --help` for more options.
> hubstats [master●] %
> 
> hubstats [master●] % rake hubstats:install:migrations
> rake aborted!
> Don't know how to build task 'hubstats:install:migrations' (see --tasks)
> /Users/martinmalek/.rvm/gems/ruby-2.3.0@hubstats/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
> /Users/martinmalek/.rvm/gems/ruby-2.3.0@hubstats/bin/ruby_executable_hooks:15:in `eval'
> /Users/martinmalek/.rvm/gems/ruby-2.3.0@hubstats/bin/ruby_executable_hooks:15:in `<main>'
> (See full trace by running task with —trace)
> ```
> What am I missing?

My first question is, in your application, did you write `gem 'hubstats', '~> 0.11.0'` in your Gemfile? After writing that, you could run:
```
$ gem install bundler
# will install bundler if not previously installed
$ bundle install
# will make sure to install Hubstats from RubyGems
```

Then try re-running `rails generate hubstats:install`.

**Comment by martinmalek** [comment]
Maybe I misunderstood how to run this.
I’m trying to run it standalone.
Do you mean I should create a new rails app and include hubstats in it?

**Comment by martinmalek** [comment]
Fixed it by funning it as a gem. Sorry for not getting that part.

**Comment by emmasax1** [comment]
Nope, that's completely fine! Glad we got it figured out!
