### ISSUE TITLE
Rake migration adding columns to text body breaks when comment bodies are fancy

### ISSUE THREAD

**Issue by emma-sax4** [sportngin/hubstats#99]
I think that having a comment that includes gifs and/or emojis tends to break. Unsure why..... Webhooks works correctly. The error is:
`ActiveRecord::StatementInvalid: Mysql2::Error: Incorrect string value`

And the stacktrace leads to here:
`/app/models/hubstats/comment.rb:47:in `create_or_update'`

**Comment by elliott-beach** [comment]
I encountered this issue when attempting to set up the project.
The problem is that the db needs to use `utf8mb4` encoding. See https://blog.arkency.com/2015/05/how-to-store-emoji-in-a-rails-app-with-a-mysql-database/.

**Comment by emma-sax4** [comment]
This is probably still an issue, but I don't like having stale issues/PRs floating around. SportsEngine got away from the problem by removing the `hubstats_comments` table in the DB, and now we don't even load comments even more.
